lang: en_US

# Radiation accumulation/decay rate (per second)
accumulationRate: 0.1
decayRate: 0.2

# Threshold values of radiation levels:
level2Threshold: 6.0
level3Threshold: 9.0
level4Threshold: 15.0
level5Threshold: 25.0

# Base damage dealt at level 4 (at level 5, damage is doubled)
baseDamage: 1.0

# Radiation sensor (dosimeter) settings
radiation-sensor:
  hide-recipe: true
  glow-effect: true
  recipe:
    shape:
      - "ORD"
      - "RCR"
      - "ARS"
    ingredients:
      R: REDSTONE
      C: COMPASS
      O: OBSERVER
      D: DAYLIGHT_DETECTOR
      A: COMPARATOR
      S: SCULK_SENSOR
